### ISSUE TITLE
FSE - Pagination

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#236]
## Feature description

Support Pagination on Archive Pages

Current archive page pagination design: 

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/5015489/140277621-5fe04a5d-0cea-4bd9-9b22-334b11136877.png">

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Allow archive page templates to support pagination.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Last link in pagination is not working as expected.

**Comment by felipebochehin87** [comment]
**NOK:**

When I reach the last page of the archives, I am still able to click on the "next page" button, which takes me to a "Page not found". Testing locally with the current version of the pagination, when I reach the last page, "next page" and "last page" buttons are disabled, the same way it happens when I am on the first page ("previous page" and "first page" buttons are disabled).

**This is how it looks on FSE:** 

https://user-images.githubusercontent.com/96055551/152333073-939ab9c0-fad9-4550-8960-18af2bf04944.mp4

**This is how it looks on the current version (tested locally):**

https://user-images.githubusercontent.com/96055551/152333184-3362c036-e512-4be9-86ea-78e45dfeaf93.mp4

**Comment by felipebochehin87** [comment]
LGTM.

When the user reaches the last page, next (>) and jump to last (>|) are disabled.
When the user reaches the first page, previous (<) and jump to first (|<) are disabled.
