### ISSUE TITLE
[M3] Components - Material Card

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#330]
## Feature description

Update Material Card component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Material card block is replaced with m3 specs according to [M3 design kit](https://www.figma.com/community/file/1035203688168086460)
* When the user opens Gutenberg page with m2 component it automatically migrates to M3

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by mattchungxwp** [comment]
Confirm with @rodydavis : Should we support elevated version of card?

**Comment by PatelUtkarsh** [comment]
We got answer to above question: We are using all 3 for now. I will add additional option in card style and other places where required.

----

Card button hover state requires `rgba(var(--md-sys-color-primary), 0.08)` 

Since that doesn't work with HEX and post CSS or any pre-processor won't able to help since our colors are dynamic we are exposing `--md-sys-color-primary-rgb: 155,64,82;` like this with rgb csv value so that we can use it as `rgba(var(--md-sys-color-primary-rgb), 0.08);` for such usecases. 

I discussed with @emeaguiar and this works for us.

Question for @rodydavis: Is there any alternate solution that material team currently uses for run time color with alpha value, or is this fine? (Currently adding such variable as it requires in components).

**Comment by felipebochehin87** [comment]
Tested locally.

1. Downgraded the theme and the plugin version
2. Added blocks to a new page: card collection, curated card collection, material/card and query loop with material card
3. Upgraded the theme and the plugin version
4. Refreshed pages - layout updated, round corners, new color, font meets the expected. Elevation styles OK.

**Comment by igruszkauy** [comment]
@PatelUtkarsh tested locally in a fresh environment (installed theme and plugin current versions) and I am having an error when adding query loop with material card:
![image](https://user-images.githubusercontent.com/2902880/182030198-eec6d235-2b1d-4a18-820d-282e25fa461e.png)

@felipebochehin87 can you please post screenshots of how you are seeing the new components migrated? I followed the steps outlined by Utkrash but I am not sure I am seeing what's expected.
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/2902880/182030697-bdc14e53-a145-4436-9b4c-e26cd18b3e1c.png">

**Comment by felipebochehin87** [comment]
@igruszkauy @PatelUtkarsh

Using an existing site (videos below):

1. I see the same message "This block has encountered an error and cannot be previewed." However, when I update the theme and the plugin to 0.6.1, things work.
2. Tables and other elements look good after updating the plugin and the theme.

Using a fresh install (images below):

1. I see the same as Ivana, block doesn't load, error messages on the components I added...
2. Some layout issues, as can be seen on the two images below

https://user-images.githubusercontent.com/96055551/182359128-373e6dc8-d45d-4483-8dfd-f2a3b5d85373.mp4

https://user-images.githubusercontent.com/96055551/182359166-9d77db39-6b56-4172-9d80-3fa421ca0b1e.mp4

![image](https://user-images.githubusercontent.com/96055551/182361008-935d3671-4165-49dc-955d-431ec64168c4.png)

![image](https://user-images.githubusercontent.com/96055551/182362091-7d044bf2-830e-4c71-9494-52eaf54afb5b.png)

**Comment by PatelUtkarsh** [comment]
> 1. I see the same message "This block has encountered an error and cannot be previewed." However, when I update the theme and the plugin to 0.6.1, things work.

This is expected since there is error and we have hotfix to release with 0.6.1 (issue happening on 0.6.0).

Note: We should not directly use material card for query loop block (And use query loop with template for material card). 

For corner radius: I've created ticket earlier #384 using which we will update all default radius.

Here is a demo with fresh install (note there are no posts because it's clean install): 

https://user-images.githubusercontent.com/5015489/182380385-f3809495-bde1-4924-9eb3-216b50fcfdb4.mp4

**Comment by igruszkauy** [comment]
@PatelUtkarsh:

1.  I am trying to replicate the steps in your video and with a fresh install I am getting this error when adding "Query loop with material card" block:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/2902880/183222128-2ccf6ea3-cd94-4001-a94d-527c1c219cfb.png">
I have installed the demo content.

Apart from this, and the fact that I need to select the source color if I am on a fresh install, all looks good.

**Comment by PatelUtkarsh** [comment]
Helllo @igruszkauy, Which plugin version are you using?

**Comment by igruszkauy** [comment]
@PatelUtkarsh new install, I updated the plugin Version 0.6.0 and theme version, both installed from WP

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, Yes this is known issue with 0.6.0 - we are fixing it in #393 (0.6.1).

**Comment by igruszkauy** [comment]
@PatelUtkarsh perfect, then closing because the rest of the behavior is as expected
