### ISSUE TITLE
[M3] Color and Background color to support M3 tokens

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#354]
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* The user can use M3 tokens from Gutenberg

## Implementation brief

* 

## QA testing instructions

* User is able to choose any of the M3 colors registred

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Using Gutenberg's default color picker, It should display m3 tokens for text and background colors. 

@emeaguiar This is different from customizer.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/5015489/176171878-a3085fd2-efee-4f79-abe0-e7d9c8666a86.png">

**Comment by mattchungxwp** [comment]
Confirm with @rodydavis : Should we continue to use static palette or generated M3 colors?

**Comment by rodydavis** [comment]
Use the new generated ones!

**Comment by PatelUtkarsh** [comment]
QA note: Gutenberg text and background color should show m3 token: 

<img width="629" alt="image" src="https://user-images.githubusercontent.com/5015489/178948430-fa35e960-6302-425b-b16b-b79f4256f702.png">

**Comment by felipebochehin87** [comment]
@igruszkauy @PatelUtkarsh the functionality looks good so far. Tested using https://dev-mdc-web.pantheonsite.io/wp-admin/post.php?post=2665&action=edit

1. Added a Media & Text block
2. Clicked on the text
3. Opened More Settings Menu
4. Changed color (background and text)
5. Selected default colors and also custom colors

My questions are (and I'm opening as questions because I'd like to confirm if that's expected before saying it's a bug):

1. We have a "check" on the selected color, but this check is white. This makes the check invisible when we select the white color. Is it possible (and necessary) to change the color of the check when the selected color is white so that the check is visible?
2. The custom color is not displayed on the list of colors. Is that expected? Click on Custom color, select a color, collapse the color picker, expand the color picker - the custom color remains applied to the text, but it is not listed in the color picker. Should we display the color and the check on it to show what color is selected?


![expanded](https://user-images.githubusercontent.com/96055551/179207026-94933c21-4c21-4f23-be5f-51561195423d.png)
![collapsed](https://user-images.githubusercontent.com/96055551/179207034-0c108680-7f11-43f9-b5c3-0a413da02df7.png)

**Comment by igruszkauy** [comment]
@felipebochehin87 thank you for the questions!

- The check and font color of the name of the color should be white/black depending on the selected color
- Custom color is displayed, I think you need to re-test, this is what I am seeing now: ![Uploading Screen Shot 2022-07-15 at 11.47.52.png…]()
@emeaguiar I think I missed what we agreed with the name of the color? Currently showing the css name

**Comment by felipebochehin87** [comment]
Thanks @igruszkauy !!

About my second question: I thought that the custom color was supposed to be displayed along with the other colors, in a circle, just like the others. Now I see, the custom will be displayed on the rectangle. Thanks! :)

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/2744-2/

1. Added a paragraph, I can change the color and background using M3 colorshttps://dev-mdc-web.pantheonsite.io/2744-2/
2. When updating source color from customizer, the color and background from paragraph are updated
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/2902880/186709178-eaf90fe6-e32f-4a79-b40e-4fa95a8b9fe9.png">

Known issues that need to be handled by core:
1. Name of the color to be more user friendly
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2902880/186709747-a6d57e35-52ef-4922-a744-bfd688d96ca9.png">

2. Color of the font for the name of the color is white and can't be seen when selecting a light color
<img width="706" alt="image" src="https://user-images.githubusercontent.com/2902880/186709772-baf6ff35-00d2-4e60-b7a0-6f5b889bdc88.png">
