### ISSUE TITLE
[M3] Component top app bar

### ISSUE THREAD

**Issue by PatelUtkarsh** [material-components/material-design-for-wordpress#404]
## Feature description

Replace m2's top app bar with m3 tokens: `@material/top-app-bar/dist/mdc.top-app-bar.css` 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment]
Top app bar: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5015489/184092358-6289d4ec-933a-4068-a248-a711ae3ef9c2.png">

QA Note: Test top app bar with m3 token.

**Comment by igruszkauy** [comment]
Verified via: https://dev-mdc-web.pantheonsite.io/

1. If I click on "Design" from the top app bar, "Design" and "Components" are visually selected but it takes me to "Components". Same happens when selecting other items.
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/2902880/184407837-b161cd86-a398-4a21-b07b-f836a6dad903.png">
Both are also selected in drawer:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/2902880/184407902-2b380c85-f90d-4af2-a825-906431e741a9.png">

@PatelUtkarsh  Sending back for review

**Comment by PatelUtkarsh** [comment]
Hello @igruszkauy, This is because both design and components points to same link. https://dev-mdc-web.pantheonsite.io/blog-2/.

**Comment by igruszkauy** [comment]
@PatelUtkarsh 
Updated the menus links and it's working as expected:
![image](https://user-images.githubusercontent.com/2902880/184865581-dad9383d-5ec3-4b71-a490-cb0b3b844849.png)
